server:
  port: 8080
  max-http-header-size: 81920

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.134.49:1752/xiyoumusic?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: yellowdoge
    password: xiong962464!
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://111.230.134.49:1752/xiyoumusic?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: yellowdoge
      password: xiong962464!
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connection-init-sqls: set names utf8mb4
mybatis:
  type-aliases-package: com.yellowdoge.app.xiyoumusic.model
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql


#spring.mvc.static-path-pattern: /tx/*
# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/